# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6581584db3120db53b11dea9839bff89165a5e6a08bdc73176601e1dc6de5f88fa57c081883fa36008157ad217748b054a9c1b2088d74e324ebcc967991b4ddb

test:
  secret_key_base: a2a47e6f8ad7336d46cd612eb1e546137aa8e82e3b9621ac357e8a342d0ebdb6973ddd9959ad819bacfacb5c1016ede3615897e894f25b4fc97e1b282db26f88

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
